-- Purpose: per-step timings for a costing part's processing run.
--
-- Written because "why did this part take 5m32s?" was only answerable by
-- correlating consumer logs, service output directories and file mtimes by
-- hand. One row per step per run makes it a query, and lets the workspace show
-- where the time actually went.
--
-- A run is a single pass over the part (one NewCostingParts message). Re-runs
-- append a new RunId rather than overwriting, so a regression is visible as a
-- comparison against the previous run instead of silently replacing it.
--
-- Idempotent: safe to re-run.

USE RFQ;
GO

SET QUOTED_IDENTIFIER ON;
GO

IF OBJECT_ID('dbo.CostingPartStageTimings') IS NULL
BEGIN
    CREATE TABLE dbo.CostingPartStageTimings (
        ID              INT IDENTITY(1,1) NOT NULL
            CONSTRAINT PK_CostingPartStageTimings PRIMARY KEY,
        CostingPartID   INT           NOT NULL
            CONSTRAINT FK_CostingPartStageTimings_CostingParts
                FOREIGN KEY REFERENCES dbo.CostingParts(ID),

        -- Groups the steps of one pass. Generated by the consumer.
        RunId           NVARCHAR(40)  NOT NULL,
        -- Order within the run, so steps display in execution order even when
        -- two finish in the same millisecond.
        Sequence        INT           NOT NULL,

        -- Stable key, e.g. 'title-block'. Label is what the UI shows.
        Stage           NVARCHAR(64)  NOT NULL,
        Label           NVARCHAR(128) NULL,

        StartTime       DATETIME      NOT NULL,
        EndTime         DATETIME      NULL,
        -- Denormalised so the UI does not depend on the server's clock maths,
        -- and so a step killed mid-flight still shows how far it got.
        DurationMs      INT           NULL,

        -- running | completed | failed | skipped
        Status          NVARCHAR(20)  NOT NULL
            CONSTRAINT DF_CPST_Status DEFAULT ('running'),
        -- Error text, or a note such as which template was used.
        Detail          NVARCHAR(400) NULL,

        InsertDate      DATETIME NOT NULL CONSTRAINT DF_CPST_InsertDate   DEFAULT (GETDATE()),
        InsertUserId    INT      NOT NULL CONSTRAINT DF_CPST_InsertUserId DEFAULT (1),
        UpdateDate      DATETIME NULL,
        UpdateUserId    INT      NULL,
        DeleteDate      DATETIME NULL,
        DeleteUserId    INT      NULL,
        IsActive        SMALLINT NOT NULL CONSTRAINT DF_CPST_IsActive DEFAULT (1)
    );

    -- The workspace always asks for one part's most recent run.
    CREATE INDEX IX_CostingPartStageTimings_Part
        ON dbo.CostingPartStageTimings (CostingPartID, RunId, Sequence)
        INCLUDE (Stage, Status, DurationMs);
END
GO

SELECT COUNT(*) AS ColumnCount FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'CostingPartStageTimings';
GO
