-- Generated by seed_machine_pictures.py.
-- Only fills machines that still have no picture, so re-running
-- it cannot overwrite a real one.
USE RFQ;
GO
SET QUOTED_IDENTIFIER ON;
GO

UPDATE dbo.Machines SET Picture = 'Machines/00000/00000001_2r29tqlr0vlg5.png', UpdateDate = GETDATE() WHERE ID = 1 AND (Picture IS NULL OR Picture = '');
UPDATE dbo.Machines SET Picture = 'Machines/00000/00000002_1h4uj38jygedq.png', UpdateDate = GETDATE() WHERE ID = 2 AND (Picture IS NULL OR Picture = '');
UPDATE dbo.Machines SET Picture = 'Machines/00000/00000003_udflnt9hd7l08.png', UpdateDate = GETDATE() WHERE ID = 3 AND (Picture IS NULL OR Picture = '');
UPDATE dbo.Machines SET Picture = 'Machines/00000/00000004_cyz5rdbq7b9hr.png', UpdateDate = GETDATE() WHERE ID = 4 AND (Picture IS NULL OR Picture = '');
UPDATE dbo.Machines SET Picture = 'Machines/00000/00000005_y5wpnp3618bmp.png', UpdateDate = GETDATE() WHERE ID = 5 AND (Picture IS NULL OR Picture = '');
UPDATE dbo.Machines SET Picture = 'Machines/00000/00000006_2ljvs66tp3yug.png', UpdateDate = GETDATE() WHERE ID = 6 AND (Picture IS NULL OR Picture = '');
UPDATE dbo.Machines SET Picture = 'Machines/00000/00000007_gt4klampsymg6.png', UpdateDate = GETDATE() WHERE ID = 7 AND (Picture IS NULL OR Picture = '');
UPDATE dbo.Machines SET Picture = 'Machines/00000/00000008_edaijlaixhkyd.png', UpdateDate = GETDATE() WHERE ID = 8 AND (Picture IS NULL OR Picture = '');
UPDATE dbo.Machines SET Picture = 'Machines/00000/00000009_iy3b71i56mbq9.png', UpdateDate = GETDATE() WHERE ID = 9 AND (Picture IS NULL OR Picture = '');
UPDATE dbo.Machines SET Picture = 'Machines/00000/00000010_zkzcdslwvxj2e.png', UpdateDate = GETDATE() WHERE ID = 10 AND (Picture IS NULL OR Picture = '');
UPDATE dbo.Machines SET Picture = 'Machines/00000/00000011_ft2sxja2j0ape.png', UpdateDate = GETDATE() WHERE ID = 11 AND (Picture IS NULL OR Picture = '');
UPDATE dbo.Machines SET Picture = 'Machines/00000/00000012_jx9qiu5b6q0hu.png', UpdateDate = GETDATE() WHERE ID = 12 AND (Picture IS NULL OR Picture = '');
UPDATE dbo.Machines SET Picture = 'Machines/00000/00000013_g1l4rofgjc0kj.png', UpdateDate = GETDATE() WHERE ID = 13 AND (Picture IS NULL OR Picture = '');
UPDATE dbo.Machines SET Picture = 'Machines/00000/00000014_amdhztaeqi7cr.png', UpdateDate = GETDATE() WHERE ID = 14 AND (Picture IS NULL OR Picture = '');
UPDATE dbo.Machines SET Picture = 'Machines/00000/00000015_av9ma67i1bkzp.png', UpdateDate = GETDATE() WHERE ID = 15 AND (Picture IS NULL OR Picture = '');
UPDATE dbo.Machines SET Picture = 'Machines/00000/00000016_gfg0y375biuvr.png', UpdateDate = GETDATE() WHERE ID = 16 AND (Picture IS NULL OR Picture = '');
UPDATE dbo.Machines SET Picture = 'Machines/00000/00000017_f9fy1isykdkwf.png', UpdateDate = GETDATE() WHERE ID = 17 AND (Picture IS NULL OR Picture = '');
UPDATE dbo.Machines SET Picture = 'Machines/00000/00000018_bimjy3pa1eja1.png', UpdateDate = GETDATE() WHERE ID = 18 AND (Picture IS NULL OR Picture = '');
UPDATE dbo.Machines SET Picture = 'Machines/00000/00000019_m7jvx672r2lic.png', UpdateDate = GETDATE() WHERE ID = 19 AND (Picture IS NULL OR Picture = '');
UPDATE dbo.Machines SET Picture = 'Machines/00000/00000020_c648sn3khh8hb.png', UpdateDate = GETDATE() WHERE ID = 20 AND (Picture IS NULL OR Picture = '');
UPDATE dbo.Machines SET Picture = 'Machines/00000/00000021_ej449o9avallk.png', UpdateDate = GETDATE() WHERE ID = 21 AND (Picture IS NULL OR Picture = '');
UPDATE dbo.Machines SET Picture = 'Machines/00000/00000022_lflzrl2n0nemh.png', UpdateDate = GETDATE() WHERE ID = 22 AND (Picture IS NULL OR Picture = '');
UPDATE dbo.Machines SET Picture = 'Machines/00000/00000023_7gq9qnd6k9edj.png', UpdateDate = GETDATE() WHERE ID = 23 AND (Picture IS NULL OR Picture = '');
UPDATE dbo.Machines SET Picture = 'Machines/00000/00000024_nqm8d1mmbkf8i.png', UpdateDate = GETDATE() WHERE ID = 24 AND (Picture IS NULL OR Picture = '');
UPDATE dbo.Machines SET Picture = 'Machines/00000/00000025_ghhi69u95m48i.png', UpdateDate = GETDATE() WHERE ID = 25 AND (Picture IS NULL OR Picture = '');
UPDATE dbo.Machines SET Picture = 'Machines/00000/00000026_38kqyvzkoguae.png', UpdateDate = GETDATE() WHERE ID = 26 AND (Picture IS NULL OR Picture = '');
UPDATE dbo.Machines SET Picture = 'Machines/00000/00000027_0yod7j3thx28a.png', UpdateDate = GETDATE() WHERE ID = 27 AND (Picture IS NULL OR Picture = '');
UPDATE dbo.Machines SET Picture = 'Machines/00000/00000028_isat3d4f60h22.png', UpdateDate = GETDATE() WHERE ID = 28 AND (Picture IS NULL OR Picture = '');
UPDATE dbo.Machines SET Picture = 'Machines/00000/00000029_fdvolvnn528hr.png', UpdateDate = GETDATE() WHERE ID = 29 AND (Picture IS NULL OR Picture = '');
UPDATE dbo.Machines SET Picture = 'Machines/00000/00000030_se1khh4dzbai1.png', UpdateDate = GETDATE() WHERE ID = 30 AND (Picture IS NULL OR Picture = '');
UPDATE dbo.Machines SET Picture = 'Machines/00000/00000031_95b9h3g8mmdqz.png', UpdateDate = GETDATE() WHERE ID = 31 AND (Picture IS NULL OR Picture = '');
UPDATE dbo.Machines SET Picture = 'Machines/00000/00000032_mo3gzmi8c4d2q.png', UpdateDate = GETDATE() WHERE ID = 32 AND (Picture IS NULL OR Picture = '');
UPDATE dbo.Machines SET Picture = 'Machines/00000/00000033_ldtid10dk8hbl.png', UpdateDate = GETDATE() WHERE ID = 33 AND (Picture IS NULL OR Picture = '');
UPDATE dbo.Machines SET Picture = 'Machines/00000/00000034_dt057bi6cud0i.png', UpdateDate = GETDATE() WHERE ID = 34 AND (Picture IS NULL OR Picture = '');
UPDATE dbo.Machines SET Picture = 'Machines/00000/00000035_efy7n893m3dth.png', UpdateDate = GETDATE() WHERE ID = 35 AND (Picture IS NULL OR Picture = '');
UPDATE dbo.Machines SET Picture = 'Machines/00000/00000036_iynzqan45uwn0.png', UpdateDate = GETDATE() WHERE ID = 36 AND (Picture IS NULL OR Picture = '');
UPDATE dbo.Machines SET Picture = 'Machines/00000/00000037_ays5a9l0g613y.png', UpdateDate = GETDATE() WHERE ID = 37 AND (Picture IS NULL OR Picture = '');
UPDATE dbo.Machines SET Picture = 'Machines/00000/00000039_nzvlqxkbi98c5.png', UpdateDate = GETDATE() WHERE ID = 39 AND (Picture IS NULL OR Picture = '');
UPDATE dbo.Machines SET Picture = 'Machines/00000/00000040_f6h27npla7uxt.png', UpdateDate = GETDATE() WHERE ID = 40 AND (Picture IS NULL OR Picture = '');
UPDATE dbo.Machines SET Picture = 'Machines/00000/00000041_jv8bujn1fjv09.png', UpdateDate = GETDATE() WHERE ID = 41 AND (Picture IS NULL OR Picture = '');
UPDATE dbo.Machines SET Picture = 'Machines/00000/00000042_7pxv5g2wy3ali.png', UpdateDate = GETDATE() WHERE ID = 42 AND (Picture IS NULL OR Picture = '');
GO
