"""Gives every pictureless machine a picture, picked at random from the ones
already uploaded.

Serenity's ImageUploadEditor does not store just a path -- each upload is a
triple under the upload root:

    Machines/00000/<id:08>_<code>.png        the image
    Machines/00000/<id:08>_<code>_t.jpg      the thumbnail the grid renders
    Machines/00000/<id:08>_<code>.png.meta   sidecar naming the owning row

Copying only the .png would give a grid full of broken thumbnails, and a .meta
carrying someone else's EntityId would misreport which row owns the file. So
this copies all three and rewrites the sidecar for the target machine.

Writes the files, then emits SQL to point the rows at them plus a matching
rollback script. Nothing touches the database directly -- run the emitted SQL
yourself so the change is reviewable.

    python .mssql-scripts/seed_machine_pictures.py            # dry run
    python .mssql-scripts/seed_machine_pictures.py --apply
"""

import json
import os
import random
import shutil
import string
import sys

UPLOAD_ROOT = r"C:\Aizera\DSRFQ\DSRFQ.Web\App_Data\upload"
GROUP = os.path.join("Machines", "00000")
SRC_DIR = os.path.join(UPLOAD_ROOT, GROUP)
OUT_DIR = os.path.dirname(os.path.abspath(__file__))

APPLY = "--apply" in sys.argv
# Fixed so a re-run reproduces the same assignment rather than reshuffling
# everything and orphaning the files the previous run wrote.
random.seed(20260821)


def code():
    """A 13-character lowercase code, matching what Serenity generates."""
    return "".join(random.choice(string.ascii_lowercase + string.digits)
                   for _ in range(13))


def sources():
    """One entry per distinct image already uploaded for a machine."""
    seen, out = set(), []
    for name in sorted(os.listdir(SRC_DIR)):
        if not name.endswith(".png"):
            continue
        stem = name[:-4]
        png = os.path.join(SRC_DIR, name)
        thumb = os.path.join(SRC_DIR, stem + "_t.jpg")
        meta = os.path.join(SRC_DIR, name + ".meta")
        if not (os.path.exists(thumb) and os.path.exists(meta)):
            print(f"  skipping {name}: no thumbnail or sidecar next to it")
            continue
        # De-duplicate by content: three of the five uploads are the same image.
        key = (os.path.getsize(png), open(png, "rb").read(4096))
        if key in seen:
            continue
        seen.add(key)
        out.append({"stem": stem, "png": png, "thumb": thumb, "meta": meta})
    return out


def main():
    if not os.path.isdir(SRC_DIR):
        sys.exit(f"no upload folder at {SRC_DIR}")

    targets = [int(a) for a in sys.argv[1:] if a.isdigit()]
    if not targets:
        sys.exit("pass the machine ids to fill, e.g. ... 1 2 3\n"
                 "(get them from: SELECT ID FROM dbo.Machines "
                 "WHERE IsActive=1 AND (Picture IS NULL OR Picture=''))")

    pool = sources()
    print(f"{len(pool)} distinct source image(s): "
          f"{', '.join(s['stem'] for s in pool)}")
    if not pool:
        sys.exit("nothing to copy")

    updates, rollback, assigned = [], [], []
    for machine_id in targets:
        src = random.choice(pool)
        stem = f"{machine_id:08d}_{code()}"
        rel = f"Machines/00000/{stem}.png"

        if APPLY:
            shutil.copyfile(src["png"], os.path.join(SRC_DIR, stem + ".png"))
            shutil.copyfile(src["thumb"], os.path.join(SRC_DIR, stem + "_t.jpg"))
            with open(src["meta"], encoding="utf-8") as fh:
                meta = json.load(fh)
            # The sidecar says which row owns the file; copying it verbatim
            # would leave every new file claiming to belong to machine 43.
            meta["EntityId"] = str(machine_id)
            meta["OriginalName"] = os.path.basename(src["png"])
            with open(os.path.join(SRC_DIR, stem + ".png.meta"), "w",
                      encoding="utf-8") as fh:
                json.dump(meta, fh, indent=2)

        assigned.append((machine_id, src["stem"], rel))
        updates.append(f"UPDATE dbo.Machines SET Picture = '{rel}', "
                       f"UpdateDate = GETDATE() WHERE ID = {machine_id} "
                       f"AND (Picture IS NULL OR Picture = '');")
        rollback.append(f"UPDATE dbo.Machines SET Picture = NULL WHERE ID = "
                        f"{machine_id} AND Picture = '{rel}';")

    for machine_id, stem, rel in assigned:
        print(f"  machine {machine_id:>3}  <- {stem}")

    header = ("-- Generated by seed_machine_pictures.py.\n"
              "-- Only fills machines that still have no picture, so re-running\n"
              "-- it cannot overwrite a real one.\nUSE RFQ;\nGO\n"
              "SET QUOTED_IDENTIFIER ON;\nGO\n\n")
    apply_sql = os.path.join(OUT_DIR, "onetime-seed-machine-pictures.sql")
    undo_sql = os.path.join(OUT_DIR, "rollback-seed-machine-pictures.sql")
    with open(apply_sql, "w", encoding="utf-8") as fh:
        fh.write(header + "\n".join(updates) + "\nGO\n")
    with open(undo_sql, "w", encoding="utf-8") as fh:
        fh.write("-- Undo of onetime-seed-machine-pictures.sql. Clears only the\n"
                 "-- exact paths that script set, so a picture changed since is kept.\n"
                 "USE RFQ;\nGO\nSET QUOTED_IDENTIFIER ON;\nGO\n\n"
                 + "\n".join(rollback) + "\nGO\n")

    print(f"\n{'copied' if APPLY else 'DRY RUN - would copy'} "
          f"{len(assigned)} image set(s)")
    print(f"apply:    {apply_sql}")
    print(f"rollback: {undo_sql}")
    if not APPLY:
        print("\nre-run with --apply to write the files")


main()
